version: '3.2'

services:
  backend:
    image: 'todobackend'
    build:
      context: .
      dockerfile: src/main/docker/backend/Dockerfile
    container_name: backend
    ports:
    - 127.0.0.1:8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: 'todofrontend'
    build:
      context: .
      dockerfile: src/main/docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - 127.0.0.1:4200:4200
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
networks:
  app:
